### ISSUE TITLE
`build-finished` hook incompatible with sphinx v7

### ISSUE THREAD

**Issue by rossbar** [matthew-brett/nb2plots#26]
Just a heads up that we started seeing `nb2plots.runroles` errors in the NetworkX doc builds with the release of sphinx 7.0. Full error below:

```
Extension error (nb2plots.runroles):
Handler <function write_runfiles at 0x7f53fc6267a0> for event 'build-finished' threw an exception (exception: Builder.__init__() missing 1 required positional argument: 'env')
make: *** [Makefile:53: html-noplot] Error 2
```

**Comment by MridulS** [comment]
Relevant PR https://github.com/sphinx-doc/sphinx/pull/11379/

**Comment by matthew-brett** [comment]
@rossbar - does #29 work for you?

**Comment by jarrodmillman** [comment]
The new release works for us https://github.com/networkx/networkx/pull/6859. Thanks!
