### PR TITLE
Update nbconvert path to ResourcesDict in runroles.py

### LINKED ISSUE #32: nbconvert 7.9 has no attribute 'exporter'
In NX, we are getting this error with the newly released version of nbconvert:
```
Extension error (nb2plots.runroles):
Handler <function write_runfiles at 0x7fa5ad52bf40> for event 'build-finished' threw an exception (exception: module 'nbconvert' has no attribute 'exporter')
```

### PR DESCRIPTION
**Pull request by dschult**
Fixes #32 

nbconvert changed their import structure in v7.9.0 (replacing import * with import (<list of things>) and `ResourcesDict` no longer is available in `nbconvert.exporter`. Switched to `nbconvert.exporters.exporter`.

I think this new syntax will work for older versions of nbconvert. 
But the previous syntax stops working in nbconvert v7.9.0

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks @dschult - kind of you to add a fix - but I beat you to it with a refactor at #33 !   Closing in favor of that PR.
